
name: Phoenix Test Automation Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
   - cron: "30 18 * * *"
   - cron: "30 17 * * *"
   
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        type: choice
        options: [qa,uat,dev]
        default: qa
        required: true
        
      suiteXmlFile:
        description: "Suite File"
        type: choice
        options: [testng.xml,smole.xml,sanity.xml]
        default: testng.xml
        required: true
        

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Execute the Test Automation Framework
      run: mvn clean test -DsuiteXmlFile="${{ github.event.inputs.suiteXmlFile }}" -Denv="${{ github.event.inputs.env }}"

    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v6.0.0
      with:
        name: Surefire Reports
        path: target/surefire-reports
        retention-days: 10
        

